services:
  # A Docker web service
  - type: web
    name: hello-render
    env: docker
    repo: https://github.com/raydoom/hello-render.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
